

Error:
```
postgres duplicate key value violates unique constraint table_system_pkey
```

Fix:

Django:
```
python manage.py sqlsequencereset app_name | python manage.py dbshell
```

SQL:
```
SELECT setval('id_sequence', (SELECT MAX(id) FROM the_table)+1);
```

Reason:

When restoring a database from a backup, the sequence variable Postgres uses to increment the ID does not get set. Thus you have to manually set this key.